/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleUpdateFull { 
    mod_number: any | null;
    price: any | null;
    unit_id: any | null;
    name_de: any | null;
    name_it: any | null;
    description_de: any | null;
    description_it: any | null;
    vat_id: any | null;
    favorite?: any | null;
    category_ids: any | null;
}

