/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatRecipient { 
    email: any | null;
    tel: any | null;
    firstname: any | null;
    secondname: any | null;
    cost: any | null;
    innovaphone_user: any | null;
    innovaphone_pass: any | null;
    notifications: any | null;
    id: any | null;
    fullname: any | null;
}

