/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactCreate { 
    name: any | null;
    name1?: any | null;
    tel: any | null;
    mail: any | null;
    note: any | null;
    id: any | null;
    lastname: any | null;
}

