/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DescriptiveArticleCreate { 
    name: any | null;
    amount: any | null;
    description: any | null;
    single_price: any | null;
    discount: any | null;
    alternative: any | null;
    descriptive_articles?: any | null;
    vat_id: any | null;
    unit_id?: any | null;
}

