/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lock } from './lock';


export interface IngoingInvoice { 
    lock: Lock;
    number: any | null;
    name: any | null;
    date: any | null;
    payment_date: any | null;
    total: any | null;
    iva: any | null;
    cf: any | null;
    id: any | null;
    timestamp: any | null;
    payments: any | null;
    paid: any | null;
    xml?: any | null;
    xml_server?: any | null;
    date_formatted: any | null;
}

