/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatus } from './jobStatus';
import { UserEssential } from './userEssential';
import { Address } from './address';
import { OrderableType } from './orderableType';
import { Client } from './client';
import { Lock } from './lock';


export interface Job { 
    type: OrderableType;
    name: any | null;
    id: any | null;
    displayable_name: any | null;
    lock: Lock;
    description: any | null;
    timestamp: any | null;
    address: Address;
    year: any | null;
    code: any | null;
    client: Client;
    archive: any | null;
    path: any | null;
    status: JobStatus;
    sub_jobs: any | null;
    is_main: any | null;
    is_sub: any | null;
    is_mini: any | null;
    responsible: UserEssential;
    main_job_id?: any | null;
    completion: any | null;
}
export namespace Job {
}


