/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { Car } from './car';
import { Job } from './job';


export interface Journey { 
    distance_km: any | null;
    date: any | null;
    reason?: any | null;
    id: any | null;
    user: UserEssential;
    car: Car;
    job?: Job;
}

