/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferCreate { 
    date: any | null;
    in_price_included: any | null;
    validity: any | null;
    payment: any | null;
    delivery: any | null;
    discount_amount: any | null;
    discount_percentage: any | null;
    material_description: any | null;
    material_description_title: any | null;
    job_id: any | null;
    descriptive_articles: any | null;
    vat_id: any | null;
}

