/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { Unit } from './unit';


export interface OrderedArticle { 
    amount: any | null;
    discount: any | null;
    custom_description: any | null;
    price: any | null;
    comment: any | null;
    position: any | null;
    request: any | null;
    id: any | null;
    ordered_unit: Unit;
    article: Article;
    vat: any | null;
}

