/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderedArticleCreate { 
    amount: any | null;
    discount: any | null;
    custom_description: any | null;
    price: any | null;
    comment: any | null;
    position: any | null;
    request: any | null;
    ordered_unit_id: any | null;
    article_id: any | null;
    vat_id: any | null;
}

