/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Vat } from './vat';
import { Lock } from './lock';


export interface OutgoingInvoice { 
    lock: Lock;
    number: any | null;
    date: any | null;
    payment_condition: any | null;
    payment_date: any | null;
    name: any | null;
    vat_number: any | null;
    fiscal_code: any | null;
    codice_destinatario: any | null;
    pec: any | null;
    isCompany: any | null;
    id: any | null;
    timestamp: any | null;
    pdf?: any | null;
    payments: any | null;
    descriptive_articles: any | null;
    reminders: any | null;
    vat: Vat;
    job_id: any | null;
    full_price_without_vat: any | null;
    full_vat_amount: any | null;
    full_price_with_vat: any | null;
    client_name: any | null;
    paid: any | null;
    address: Address;
}

