/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Country } from './country';


export interface Address { 
    name: any | null;
    street_number: any | null;
    city: any | null;
    cap: any | null;
    id: any | null;
    country: Country;
    address_1: any | null;
    address_2: any | null;
    country_name: any | null;
}

