/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Country } from './country';


export interface Address { 
    address_1: string;
    address_2: string;
    cap: string;
    city: string;
    country: Country;
    country_name: string;
    id: number;
    name: string;
    street_number: string;
}

