/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleChange } from './orderedArticleChange';


export interface ArticleUpdatedEvent { 
    name: string | null;
    'new': OrderedArticleChange;
    old: OrderedArticleChange;
    orderId: number;
    orderedArticleId: number;
    type: ArticleUpdatedEvent.TypeEnum;
}
export namespace ArticleUpdatedEvent {
    export const TypeEnum = {
        ArticleUpdated: 'article_updated'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


