/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Vat } from './vat';
import { Text } from './text';
import { Unit } from './unit';
import { Lock } from './lock';


export interface Article { 
    categories: Array<Category>;
    deleted: boolean;
    description: Text;
    favorite: boolean;
    id: number;
    lock: Lock;
    mod_number: string;
    name: Text;
    price: number;
    unit: Unit;
    vat: Vat;
}

