/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';


export interface ArticleMovedEvent { 
    orderedArticle: OrderedArticleSnapshot;
    sourceOrderDeleted: boolean;
    sourceOrderId: number;
    sourceOrderableId: number | null;
    sourceOrderableName: string | null;
    targetOrderCreated: boolean;
    targetOrderId: number;
    targetOrderableId: number;
    targetOrderableName: string;
    type: ArticleMovedEvent.TypeEnum;
}
export namespace ArticleMovedEvent {
    export const TypeEnum = {
        ArticleMoved: 'article_moved'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


