/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';


export interface ArticlesMovedEvent { 
    createdOrderBundleId: number | null;
    orderedArticles: Array<OrderedArticleSnapshot>;
    sourceOrderBundleId: number | null;
    sourceOrderId: number;
    sourceOrderableId: number | null;
    sourceOrderableName: string | null;
    targetOrderBundleId: number | null;
    targetOrderId: number;
    targetOrderableId: number;
    targetOrderableName: string;
    type: ArticlesMovedEvent.TypeEnum;
}
export namespace ArticlesMovedEvent {
    export const TypeEnum = {
        ArticlesMoved: 'articles_moved'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


