/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Text } from './text';
import { Lock } from './lock';


export interface ArticleSmall { 
    id: number;
    lock: Lock;
    mod_number: string;
    name: Text;
    price: number;
}

