/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleCreateV2 { 
    favorite: boolean;
    modNumber: string;
    nameDE: string;
    nameIT: string;
    price: number;
    supplierID: number;
    unitID: number;
}

