/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';


export interface ArticleDeletedEvent { 
    orderDeleted: boolean;
    orderedArticle: OrderedArticleSnapshot;
    type: ArticleDeletedEvent.TypeEnum;
}
export namespace ArticleDeletedEvent {
    export const TypeEnum = {
        ArticleDeleted: 'article_deleted'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


