/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';


export interface ArticleOrderedEvent { 
    articleCreated: boolean;
    orderedArticle: OrderedArticleSnapshot;
    type: ArticleOrderedEvent.TypeEnum;
}
export namespace ArticleOrderedEvent {
    export const TypeEnum = {
        ArticleOrdered: 'article_ordered'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


