/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Text } from './text';
import { Unit } from './unit';
import { Lock } from './lock';


export interface Article { 
    deleted: boolean;
    favorite: boolean;
    id: number;
    last_order_date?: string | null;
    lock: Lock;
    mod_number: string;
    name: Text;
    price: number;
    unit: Unit;
}

