/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';


export interface ChatMessage { 
    id: number;
    own: boolean;
    recipient?: UserEssential | null;
    sender: UserEssential;
    text: string;
    timestamp: string;
}

