/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientSmall { 
    cig: string;
    codice_destinatario: string;
    contact_person: string;
    cup: string;
    esigibilita_iva: string;
    fiscal_code: string;
    fullname?: string;
    id: number;
    isCompany: boolean;
    lastname: string;
    mail1: string;
    mail2: string;
    name: string;
    pec: string;
    publica_amministrazione: boolean;
    tel1: string;
    tel2: string;
    vat_number: string;
}

