/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactTypeEnum } from './contactTypeEnum';


export interface Contact { 
    id: number;
    lastname: string;
    mail: string;
    name: string;
    name1?: string | null;
    note: string;
    tel: string;
    type: ContactTypeEnum;
}
export namespace Contact {
}


