/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { DeliveryNoteReason } from './deliveryNoteReason';
import { DescriptiveArticle } from './descriptiveArticle';
import { Job } from './job';
import { Lock } from './lock';


export interface DeliveryNote { 
    articles: Array<DescriptiveArticle>;
    assigned: boolean;
    company_address: string;
    date: string;
    delivery_address: string;
    delivery_note_reason: DeliveryNoteReason;
    free: boolean;
    freight: boolean;
    id: number;
    job?: Job | null;
    lock: Lock;
    name: string;
    number: number;
    pdf?: string | null;
    timestamp: string;
    user: UserEssential;
    variations: string;
    weight: string;
}

