/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriveCreate { 
    car_id: number;
    job_id?: number | null;
    km: number;
    reason?: string | null;
}

