/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HourlyRate { 
    end_date?: string | null;
    id: number;
    rate: number;
    start_date: string;
    user_id: number;
}

