/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HourlyRateUpdateCreate { 
    end_date?: string | null;
    id?: number | null;
    rate: number;
    start_date: string;
}

