/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Liability } from './liability';
import { Lock } from './lock';


export interface IngoingInvoice { 
    cf: string;
    date: string;
    date_formatted: string;
    id: number;
    iva: string;
    liabilities: Array<Liability>;
    lock: Lock;
    name: string;
    number: string;
    payment_date: string;
    timestamp: string;
    total: number;
    xml?: string | null;
    xml_server?: string | null;
}

