/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobTypeType } from './jobTypeType';
import { AddressCreate } from './addressCreate';


export interface JobCreate { 
    address: AddressCreate;
    assembly: string;
    client_id: number;
    description: string;
    name: string;
    note?: string | null;
    production: string;
    responsible_id: number;
    type: JobTypeType;
    year: number;
}
export namespace JobCreate {
}


