/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { UserEssential } from './userEssential';
import { OrderableType } from './orderableType';
import { Client } from './client';
import { Lock } from './lock';
import { Workload } from './workload';


export interface JobForRecalculation { 
    client: Client;
    code: string;
    description: string;
    displayable_name: string;
    id: number;
    is_main: boolean;
    is_mini: boolean;
    is_sub: boolean;
    lock: Lock;
    name: string;
    ordersTo: Array<Order>;
    responsible: UserEssential;
    type: OrderableType;
    workloads: Array<Workload>;
    year: number;
}
export namespace JobForRecalculation {
}


