/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobSectionCreate { 
    job_id?: number | null;
    minutes: number;
    minutes_direction: number;
}

