/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { OrderableType } from './orderableType';
import { Client } from './client';
import { Lock } from './lock';


export interface JobSmall { 
    client: Client;
    code: string;
    description: string;
    displayable_name: string;
    id: number;
    is_main: boolean;
    is_mini: boolean;
    is_sub: boolean;
    lock: Lock;
    name: string;
    responsible: UserEssential;
    type: OrderableType;
    year: number;
}
export namespace JobSmall {
}


