/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { UserEssential } from './userEssential';


export interface Liability { 
    amount: number;
    created_at: string;
    due_date: string;
    id: number;
    ingoing_invoice_id?: number | null;
    name: string;
    open_amount: number;
    paid: boolean;
    paid_sum: number;
    payments: Array<Payment>;
    user: UserEssential;
}

