/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { EatingPlace } from './eatingPlace';


export interface Meal { 
    date: string;
    eating_place: EatingPlace;
    id: number;
    user: UserEssential;
}

