/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2EntryField } from './offerV2EntryField';


export interface OfferV2EntryOutput { 
    alternative: boolean;
    amount?: number;
    children?: Array<OfferV2EntryOutput>;
    description: string;
    elementType: string;
    fields?: Array<OfferV2EntryField>;
    id: string;
    name: string;
    offertext: string;
    price: string;
    priceChangePercent?: number | null;
    visibleOffer?: boolean;
}

