/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DescriptiveArticle } from './descriptiveArticle';
import { Vat } from './vat';
import { Lock } from './lock';


export interface Offer { 
    date: string;
    date_string?: string;
    delivery: string;
    descriptive_articles?: Array<DescriptiveArticle>;
    discount_amount: number;
    discount_percentage: number;
    full_price_with_vat?: number;
    full_price_without_vat?: number;
    full_vat_amount?: number;
    generated_number?: string;
    id: number;
    in_price_included: string;
    job_id: number;
    lock: Lock;
    material_description: string;
    material_description_title: string;
    payment: string;
    pdf?: string | null;
    timestamp: string;
    validity: string;
    vat: Vat;
}

