/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferFieldEnum } from './offerFieldEnum';


export interface OfferFieldCreatePatch { 
    calculation?: string | null;
    description: string;
    fieldType: OfferFieldEnum;
    label: string;
    unitId?: number | null;
    visible?: boolean | null;
}
export namespace OfferFieldCreatePatch {
}


