/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2EntryOutput } from './offerV2EntryOutput';
import { OfferStatementEntryOutput } from './offerStatementEntryOutput';
import { OfferV2 } from './offerV2';


export interface OfferStatement { 
    content?: Array<OfferStatementEntryOutput>;
    date: string;
    id: number;
    name: string;
    offer: OfferV2;
    offerContent: Array<OfferV2EntryOutput>;
    originalPrice: number;
    pdf: string;
    pdfServer: string;
    price: number;
    priceSubtraction: number;
    sconted_price: number;
    subPercent: number;
}

