/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferTemplateEntryOutput { 
    children?: Array<OfferTemplateEntryOutput>;
    elementId: number;
    elementType: string;
    id: string;
    name: string;
}

