/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferV2 { 
    globalAddPercent: number;
    globalPriceDiff: number;
    globalSubPercent: number;
    id: number;
    lastChanged: string;
    name: string;
}

