/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTemplateEntryInput } from './offerTemplateEntryInput';


export interface OfferTemplateCreatePatch { 
    description: string;
    name: string;
    structure: Array<OfferTemplateEntryInput>;
}

