/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferStatementEntryOutput } from './offerStatementEntryOutput';
import { OfferV2 } from './offerV2';


export interface OfferStatement { 
    content?: Array<OfferStatementEntryOutput>;
    id: number;
    name: string;
    offer: OfferV2;
    originalPrice: number;
    pdf: string;
    pdfServer: string;
    price: number;
    priceSubtraction: number;
    subPercent: number;
}

