/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferField } from './offerField';


export interface OfferElementType { 
    description: OfferField;
    fields: Array<OfferField>;
    id: number;
    name: string;
    offertext: OfferField;
    price: OfferField;
}

