/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferStatementEntryInput } from './offerStatementEntryInput';


export interface OfferStatementPatch { 
    content: Array<OfferStatementEntryInput>;
    date: string;
    name: string;
    price: number;
    priceSubtraction: number;
    subPercent: number;
}

