/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2EntryInput } from './offerV2EntryInput';


export interface OfferV2Patch { 
    content: Array<OfferV2EntryInput>;
    date: string;
    delivery: string;
    globalAddPercent: number;
    globalPriceDiff: number;
    globalSubPercent: number;
    hourlyRate: number;
    hoursSconto: number;
    inPriceIncluded: string;
    materialDescription: string;
    materialDescriptionTitle: string;
    name: string;
    number: number;
    payment: string;
    price: number;
    validity: string;
    vatId: number;
    versionName: string;
}

