/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferUnit } from './offerUnit';


export interface OfferLibraryEntry { 
    id: number;
    name: string;
    price: number;
    unit?: OfferUnit | null;
}

