/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferLibraryEntryCreatePatch { 
    libraryId: number;
    name: string;
    price: number;
    unitId: number;
}

