/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2EntryInput } from './offerV2EntryInput';


export interface OfferV2VersionCreatePatch { 
    content: Array<OfferV2EntryInput>;
    name: string;
}

