/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferV2Create { 
    delivery: string;
    inPriceIncluded: string;
    jobId: number;
    name: string;
    number: number;
    payment: string;
    validity: string;
}

