/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferUnit } from './offerUnit';
import { OfferFieldEnum } from './offerFieldEnum';


export interface OfferV2EntryField { 
    calculation?: string | null;
    default_value: string;
    description: string;
    label: string;
    libraryId?: number | null;
    mandatory: boolean;
    type: OfferFieldEnum;
    unit?: OfferUnit | null;
    value: any | null;
}
export namespace OfferV2EntryField {
}


