/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferUnit } from './offerUnit';
import { OfferFieldEnum } from './offerFieldEnum';


export interface OfferField { 
    calculation?: string | null;
    description: string;
    fieldType: OfferFieldEnum;
    id: number;
    label: string;
    unit?: OfferUnit | null;
    visible?: boolean | null;
}
export namespace OfferField {
}


