/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2Entry } from './offerV2Entry';
import { OfferV2 } from './offerV2';


export interface OfferV2Version { 
    content: Array<OfferV2Entry>;
    id: number;
    name: string;
    offerV2: OfferV2;
    timestamp: string;
}

