/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferV2EntryOutput } from './offerV2EntryOutput';


export interface OfferV2WithVersion { 
    content?: Array<OfferV2EntryOutput>;
    globalAddPercent: number;
    globalPriceDiff: number;
    globalSubPercent: number;
    id: number;
    lastChanged: string;
    name: string;
}

