/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferTemplateEntry } from './offerTemplateEntry';


export interface OfferTemplate { 
    description: string;
    id: number;
    name: string;
    structure: Array<OfferTemplateEntry>;
}

