/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleCreate } from './orderedArticleCreate';


export interface OrderUpdate { 
    articles?: Array<OrderedArticleCreate> | null;
    description: string;
}

