/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderBundleOrderTargetChangedEvent { 
    'new'?: number | null;
    old?: number | null;
    orderId: number;
    type?: OrderBundleOrderTargetChangedEvent.TypeEnum;
}
export namespace OrderBundleOrderTargetChangedEvent {
    export const TypeEnum = {
        OrderTargetChanged: 'order_target_changed'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


