/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleCreate } from './orderedArticleCreate';


export interface OrderCreate { 
    articles?: Array<OrderedArticleCreate> | null;
    description: string;
    order_from_id: number;
    order_to_id: number;
}

