/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderBundleEventType = {
    Created: 'created',
    DescriptionChanged: 'description_changed',
    DeliveryDateChanged: 'delivery_date_changed',
    OrderAdded: 'order_added',
    OrderRemoved: 'order_removed',
    OrderTargetChanged: 'order_target_changed',
    ArticleAdded: 'article_added',
    ArticleChanged: 'article_changed',
    ArticleRemoved: 'article_removed'
} as const;
export type OrderBundleEventType = typeof OrderBundleEventType[keyof typeof OrderBundleEventType];

