/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderBundleEventType = {
    OrderBundleCreated: 'order_bundle_created',
    OrderDeleted: 'order_deleted',
    ArticlesMoved: 'articles_moved',
    ArticleOrdered: 'article_ordered',
    ArticleUpdated: 'article_updated',
    ArticleMoved: 'article_moved',
    RequestsConverted: 'requests_converted',
    PricesUpdated: 'prices_updated',
    ArticleDeleted: 'article_deleted'
} as const;
export type OrderBundleEventType = typeof OrderBundleEventType[keyof typeof OrderBundleEventType];

