/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { Orderable } from './orderable';
import { Lock } from './lock';


export interface OrderBundle { 
    create_date: string;
    create_date_formatted: string;
    delivery_date: string;
    delivery_date_formatted: string;
    description: string;
    id: number;
    lock: Lock;
    order_from: Orderable;
    pdf_external?: string | null;
    pdf_internal?: string | null;
    request: boolean;
    user: UserEssential;
}

