/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { Orderable } from './orderable';
import { OrderStatusType } from './orderStatusType';
import { OrderedArticleSmall } from './orderedArticleSmall';
import { Lock } from './lock';


export interface OrderSmall { 
    articles: Array<OrderedArticleSmall>;
    create_date: string;
    create_date_formatted: string;
    delivery_date?: string | null;
    description: string;
    id: number;
    lock: Lock;
    order_from: Orderable;
    order_to: Orderable;
    pdf?: string | null;
    status: OrderStatusType;
    status_translation: string;
    user: UserEssential;
}
export namespace OrderSmall {
}


