/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Unit } from './unit';
import { ArticleSmall } from './articleSmall';


export interface OrderedArticleSmall { 
    amount: number;
    article: ArticleSmall;
    comment: string;
    id: number;
    ordered_unit: Unit;
    position: string;
    price: number;
    request: boolean;
}

