/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderedArticleCreate { 
    amount: number;
    article_id: number;
    comment: string;
    ordered_unit_id: number;
    position: string;
    price: number;
    request: boolean;
}

