/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderedArticleSnapshot { 
    amount: number;
    articleId: number;
    comment?: string | null;
    modNumber: string;
    name?: string | null;
    orderId: number;
    orderedArticleId: number;
    orderedUnitId: number;
    position?: string | null;
    price: number;
    request: boolean;
}

