/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderedArticlePriceChange { 
    name?: string | null;
    newPrice: number;
    oldPrice: number;
    orderId: number;
    orderedArticleId: number;
}

