/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderArticleCreateV2 { 
    amount: number;
    articleId: number;
    comment: string;
    modNumber: string;
    nameDe: string;
    nameIt: string;
    orderId: number;
    position: string;
    price: number;
    request: boolean;
    unitId: number;
}

