/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { Reminder } from './reminder';
import { Address } from './address';
import { DescriptiveArticle } from './descriptiveArticle';
import { Vat } from './vat';
import { PaymentTermEnum } from './paymentTermEnum';
import { Lock } from './lock';


export interface OutgoingInvoice { 
    address: Address;
    client_name: string;
    codice_destinatario: string;
    date: string;
    descriptive_articles: Array<DescriptiveArticle>;
    fiscal_code: string;
    full_price_with_vat: number;
    full_price_without_vat: number;
    full_vat_amount: number;
    id: number;
    isCompany: boolean;
    job_id: number;
    lock: Lock;
    name: string;
    number: string;
    paid: boolean;
    paymentTerms: PaymentTermEnum;
    payment_condition: string;
    payment_date: string;
    payments: Array<Payment>;
    pdf?: string | null;
    pec: string;
    reminders: Array<Reminder>;
    timestamp: string;
    vat: Vat;
    vat_number: string;
}
export namespace OutgoingInvoice {
}


