/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreate } from './addressCreate';


export interface OutgoingInvoiceCreate { 
    number: any | null;
    date: any | null;
    payment_condition: any | null;
    payment_date: any | null;
    name: any | null;
    vat_number: any | null;
    fiscal_code: any | null;
    codice_destinatario: any | null;
    pec: any | null;
    isCompany: any | null;
    descriptive_articles: any | null;
    vat_id: any | null;
    job_id: any | null;
    address: AddressCreate;
}

