/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleMovedEvent } from './articleMovedEvent';
import { ArticleUpdatedEvent } from './articleUpdatedEvent';
import { ArticlesMovedEvent } from './articlesMovedEvent';
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';
import { OrderDeletedEvent } from './orderDeletedEvent';
import { ArticleDeletedEvent } from './articleDeletedEvent';
import { OrderedArticleChange } from './orderedArticleChange';
import { RequestsConvertedEvent } from './requestsConvertedEvent';
import { ArticleOrderedEvent } from './articleOrderedEvent';
import { OrderedArticlePriceChange } from './orderedArticlePriceChange';
import { PricesUpdatedEvent } from './pricesUpdatedEvent';
import { OrderBundleCreatedEvent } from './orderBundleCreatedEvent';
import { OrderBundleSource } from './orderBundleSource';


/**
 * @type Payload
 * @export
 */
export type Payload = ArticleDeletedEvent | ArticleMovedEvent | ArticleOrderedEvent | ArticleUpdatedEvent | ArticlesMovedEvent | OrderBundleCreatedEvent | OrderDeletedEvent | PricesUpdatedEvent | RequestsConvertedEvent;

