/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PaymentTermEnum = {
    OnSight: 'on_sight',
    Gg30: 'gg_30',
    Gg14: 'gg_14'
} as const;
export type PaymentTermEnum = typeof PaymentTermEnum[keyof typeof PaymentTermEnum];

