/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticlePriceChange } from './orderedArticlePriceChange';


export interface PricesUpdatedEvent { 
    prices: Array<OrderedArticlePriceChange>;
    type: PricesUpdatedEvent.TypeEnum;
}
export namespace PricesUpdatedEvent {
    export const TypeEnum = {
        PricesUpdated: 'prices_updated'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


