/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobForRecalculation } from './jobForRecalculation';
import { WoodList } from './woodList';
import { Expense } from './expense';
import { Paint } from './paint';


export interface RecalculationV2 { 
    cost: number;
    expenses: Array<Expense>;
    id: number;
    jobs: Array<JobForRecalculation>;
    km: number;
    material_charge_percent: number;
    name: string;
    paints: Array<Paint>;
    pdf: string | null;
    totalSum: number;
    wood_lists: Array<WoodList>;
}

