/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobForRecalculation } from './jobForRecalculation';
import { WoodList } from './woodList';
import { Expense } from './expense';
import { Paint } from './paint';


export interface RecalculationV2 { 
    expenses: Array<Expense>;
    jobs: Array<JobForRecalculation>;
    material_charge_percent: number;
    paints: Array<Paint>;
    totalSum: number;
    wood_lists: Array<WoodList>;
}

