/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaintCreate } from './paintCreate';
import { ExpenseCreate } from './expenseCreate';
import { WoodListCreate } from './woodListCreate';


export interface RecalculationUpdateV2 { 
    cost: number;
    expenses: Array<ExpenseCreate>;
    km: number;
    materialChargePercent: number;
    name: string;
    paints: Array<PaintCreate>;
    woodLists: Array<WoodListCreate>;
}

