/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleSnapshot } from './orderedArticleSnapshot';


export interface RequestsConvertedEvent { 
    orderFromId: number;
    orderFromName: string;
    orderToId: number | null;
    orderToName: string | null;
    orderedArticles: Array<OrderedArticleSnapshot>;
    sourceOrderIds: Array<number>;
    targetOrderId: number;
    type: RequestsConvertedEvent.TypeEnum;
}
export namespace RequestsConvertedEvent {
    export const TypeEnum = {
        RequestsConverted: 'requests_converted'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


