/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Language } from './language';
import { OrderableType } from './orderableType';
import { Lock } from './lock';


export interface Supplier { 
    type: OrderableType;
    name: any | null;
    id: any | null;
    displayable_name: any | null;
    lock: Lock;
    mail1: any | null;
    mail2: any | null;
    tel1: any | null;
    tel2: any | null;
    contact_person: any | null;
    destination_code: any | null;
    show_in_orders: any | null;
    address: Address;
    language: Language;
    favorite: any | null;
    contacts: any | null;
    send_mail: any | null;
}
export namespace Supplier {
}


