/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreate } from './addressCreate';
import { ContactCreate } from './contactCreate';


export interface SupplierCreate { 
    address: AddressCreate;
    contact_person: string;
    contacts: Array<ContactCreate>;
    destination_code: string;
    language_code: string;
    mail1: string;
    mail2: string;
    name: string;
    send_order_to: string | null;
    show_in_orders: boolean;
    tel1: string;
    tel2: string;
}

