/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatusType } from './jobStatusType';


export interface TikTakCommission { 
    clientId: number;
    code: string;
    creationDateTime: string;
    id: number;
    isMini: boolean;
    lastModificationDateTime: string;
    name: string;
    status: JobStatusType;
    year: number;
    yearId: number;
}
export namespace TikTakCommission {
}


