/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobSmall } from './jobSmall';


export interface TikTakTimeEntryByUser { 
    id: number;
    job: JobSmall;
    lastSync: string;
    minutes: number;
}

