/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobSmall } from './jobSmall';
import { UserEssential } from './userEssential';


export interface TikTakTimeEntry { 
    id: number;
    job: JobSmall;
    lastSync: string;
    minutes: number;
    user: UserEssential;
}

