/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TokenEnum = {
    Access: 'ACCESS',
    Refresh: 'REFRESH'
} as const;
export type TokenEnum = typeof TokenEnum[keyof typeof TokenEnum];

