/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateDress { 
    belt?: boolean | null;
    ear_protection?: string | null;
    export_dress?: boolean | null;
    pants?: string | null;
    shirt?: string | null;
    shoe_model?: string | null;
    shoes?: string | null;
    sole?: string | null;
    sweater?: string | null;
}

