/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate {
    dial: string;
    email: string;
    firstname: string;
    handy: string;
    innovaphone_pass: string;
    innovaphone_user: string;
    notifications: boolean;
    password: string;
    position: string;
    secondname: string;
    tel: string;
}

