/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderEnum } from './genderEnum';


export interface UserUpdateBase { 
    address?: string | null;
    birthday?: string | null;
    birthplace?: string | null;
    city?: string | null;
    country?: string | null;
    dial: string;
    email: string;
    email_private?: string | null;
    firstname: string;
    gender?: GenderEnum | null;
    handy: string;
    notifications: boolean;
    position: string;
    postal_code?: string | null;
    secondname: string;
    tel: string;
    vat_number?: string | null;
}
export namespace UserUpdateBase {
}


