/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeEnum } from "./scopeEnum";


export interface User {
  dial: string;
  disabled: boolean;
  email: string;
  firstname: string;
  fullname: string;
  handy: string;
  id: number;
  innovaphone_pass: string;
  innovaphone_user: string;
  notifications: boolean;
  position: string;
  scopes: Array<ScopeEnum>;
  secondname: string;
  tel: string;
}

