/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderEnum } from './genderEnum';


export interface UserCreate { 
    address?: string | null;
    birthday?: string | null;
    birthplace?: string | null;
    city?: string | null;
    country?: string | null;
    dial?: string | null;
    email: string;
    email_private?: string | null;
    firstname: string;
    gender?: GenderEnum | null;
    handy?: string | null;
    innovaphone_pass?: string | null;
    innovaphone_user?: string | null;
    notifications?: boolean | null;
    password: string;
    position?: string | null;
    postal_code?: string | null;
    secondname: string;
    tel?: string | null;
    vat_number?: string | null;
}
export namespace UserCreate {
}


