/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmploymentRelationshipUpdateCreate } from './employmentRelationshipUpdateCreate';
import { HourlyRateUpdateCreate } from './hourlyRateUpdateCreate';


export interface UserUpdateEmployment { 
    employment_relationships: Array<EmploymentRelationshipUpdateCreate>;
    export_tiktak?: boolean | null;
    hourly_rates: Array<HourlyRateUpdateCreate>;
    hours_friday?: number | null;
    hours_monday?: number | null;
    hours_saturday?: number | null;
    hours_thursday?: number | null;
    hours_tuesday?: number | null;
    hours_wednesday?: number | null;
    internal_cost?: number | null;
    tag_uid?: string | null;
}

