/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserContact { 
    dial: string;
    email: string;
    firstname: string;
    fullname: string;
    handy: string;
    id: number;
    notifications: boolean;
    secondname: string;
    tel: string;
}

