/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationErrorLocInner } from './validationErrorLocInner';


export interface ValidationError { 
    ctx?: object;
    input?: any | null;
    loc: Array<ValidationErrorLocInner>;
    msg: string;
    type: string;
}

