/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VietJob { 
    end_ts?: string | null;
    filename: string;
    job_id: string;
    pieces_good?: number | null;
    pieces_planned: number;
    pieces_produced_total?: number | null;
    pieces_scrap?: number | null;
    recipe: number;
    start_ts?: string | null;
    thickness: number;
}

