/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VietLog { 
    changed_ts: string;
    from_status: string;
    id: number;
    job_id: string;
    pieces_good: number;
    pieces_scrap: number;
    to_status: string;
}

