/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { EatingPlace } from './eatingPlace';


export interface WorkDay { 
    minutes: any | null;
    id: any | null;
    date: any | null;
    user: UserEssential;
    job_sections: any | null;
    expenses: any | null;
    drives: any | null;
    eating_place?: EatingPlace;
    additional_workloads: any | null;
}

