/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkloadCreate { 
    cost?: number | null;
    job_id: number;
    minutes: number;
    minutes_direction: number;
    user_id: number;
}

