/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { Calendar } from './calendar';
import { Lock } from './lock';


export interface CalendarEntry { 
    calendar: Calendar;
    description: string;
    end_time: string;
    id: number;
    lock: Lock;
    start_time: string;
    timestamp: string;
    title: string;
    user: UserEssential;
}

