/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Language } from './language';
import { Gender } from './gender';
import { Contact } from './contact';
import { Lock } from './lock';


export interface Client { 
    address: Address;
    cig: string;
    codice_destinatario: string;
    contact_person: string;
    contacts: Array<Contact>;
    cup: string;
    esigibilita_iva: string;
    fiscal_code: string;
    fullname?: string;
    gender: Gender | null;
    id: number;
    isCompany: boolean;
    language: Language;
    lastname: string;
    lock: Lock;
    mail1: string;
    mail2: string;
    name: string;
    pec: string;
    publica_amministrazione: boolean;
    tel1: string;
    tel2: string;
    vat_number: string;
}

