/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CompanyEventEnum = {
    Vacation: 'VACATION',
    Illness: 'ILLNESS',
    Holiday: 'HOLIDAY',
    Event: 'EVENT'
} as const;
export type CompanyEventEnum = typeof CompanyEventEnum[keyof typeof CompanyEventEnum];

