/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { CompanyEventEnum } from './companyEventEnum';


export interface CompanyEvent { 
    date: string;
    event_type: CompanyEventEnum;
    id: number;
    timestamp: string;
    title: string;
    user: UserEssential;
}
export namespace CompanyEvent {
}


