/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JobStatusType = {
    JobstatusCreated: 'JOBSTATUS_CREATED',
    JobstatusAccepted: 'JOBSTATUS_ACCEPTED',
    JobstatusCompleted: 'JOBSTATUS_COMPLETED',
    JobstatusDeclined: 'JOBSTATUS_DECLINED'
} as const;
export type JobStatusType = typeof JobStatusType[keyof typeof JobStatusType];

