/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Job } from './job';


export interface JobSection { 
    id: number;
    job: Job | null;
    minutes: number;
    minutes_direction: number;
}

