/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { Car } from './car';
import { Job } from './job';


export interface Journey { 
    car: Car;
    date: string;
    distance_km: number;
    id: number;
    job: Job | null;
    reason: string | null;
    user: UserEssential;
}

