/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { Unit } from './unit';


export interface OrderedArticle { 
    amount: number;
    article: Article;
    comment: string;
    custom_description: string;
    discount: number;
    id: number;
    ordered_unit: Unit;
    position: string;
    price: number;
    request: boolean;
    vat: number;
}

