/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreate } from './addressCreate';
import { DescriptiveArticleCreate } from './descriptiveArticleCreate';


export interface OutgoingInvoiceUpdate { 
    address: AddressCreate;
    codice_destinatario: string;
    date: string;
    descriptive_articles: Array<DescriptiveArticleCreate>;
    fiscal_code: string;
    isCompany: boolean;
    name: string;
    number: string;
    payment_condition: string;
    payment_date: string;
    pec: string;
    vat_id: number;
    vat_number: string;
}

