/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ReminderLevel = {
    ReminderLevelZe: 'REMINDER_LEVEL.ZE',
    ReminderLevelLevel1: 'REMINDER_LEVEL.LEVEL1',
    ReminderLevelLevel2: 'REMINDER_LEVEL.LEVEL2',
    ReminderLevelLevel3: 'REMINDER_LEVEL.LEVEL3'
} as const;
export type ReminderLevel = typeof ReminderLevel[keyof typeof ReminderLevel];

