/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderableType } from './orderableType';
import { Lock } from './lock';


export interface Stock { 
    displayable_name: string;
    id: number;
    lock: Lock;
    name: string;
    type: OrderableType;
}
export namespace Stock {
}


