/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Right } from './right';


export interface User { 
    chat: boolean;
    cost: number;
    dial: string;
    disabled: boolean | null;
    email: string;
    employee: boolean;
    firstname: string;
    fullname: string;
    handy: string;
    hours: boolean;
    id: number;
    innovaphone_pass: string;
    innovaphone_user: string;
    notifications: boolean;
    office: boolean;
    position: string;
    rights?: Array<Right>;
    secondname: string;
    tel: string;
}

