/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalendarEntryCreate { 
    company: boolean | null;
    description: string;
    end_time: string;
    start_time: string;
    title: string;
}

