/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ContactTypeEnum = {
    Supplier: 'supplier',
    Client: 'client',
    Business: 'business',
    Management: 'management'
} as const;
export type ContactTypeEnum = typeof ContactTypeEnum[keyof typeof ContactTypeEnum];

