/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Car } from './car';
import { Job } from './job';


export interface Drive { 
    car: Car;
    id: number;
    job: Job | null;
    km: number;
    reason: string | null;
}

