/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DescriptiveArticleCreate } from './descriptiveArticleCreate';


export interface IngoingInvoiceCreate { 
    articles: Array<DescriptiveArticleCreate>;
    cf: string;
    date: string;
    iva: string;
    name: string;
    number: string;
    payment_date: string;
    total: number;
    xml_server: string | null;
}

