/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';
import { OrderBundle } from './orderBundle';
import { Orderable } from './orderable';
import { OrderStatusType } from './orderStatusType';
import { OrderedArticle } from './orderedArticle';
import { Lock } from './lock';


export interface Order { 
    articles: Array<OrderedArticle>;
    create_date: string;
    create_date_formatted: string;
    delivery_date: string | null;
    description: string;
    id: number;
    lock: Lock;
    order_bundle: OrderBundle | null;
    order_from: Orderable;
    order_to: Orderable;
    pdf: string | null;
    status: OrderStatusType;
    status_translation: string;
    user: UserEssential;
}
export namespace Order {
}


