/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Text { 
    id: number;
    key: string;
    translation?: string;
    translation_de: string;
    translation_it: string;
}

