export * from './article.service';
import { ArticleService } from './article.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './scheduler.service';
import { SchedulerService } from './scheduler.service';
export * from './viet.service';
import { VietService } from './viet.service';
export const APIS = [ArticleService, DefaultService, HealthService, SchedulerService, VietService];
