export * from './article.service';
import { ArticleService } from './article.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './job.service';
import { JobService } from './job.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './orderBundle.service';
import { OrderBundleService } from './orderBundle.service';
export * from './orderedArticle.service';
import { OrderedArticleService } from './orderedArticle.service';
export * from './recalculation.service';
import { RecalculationService } from './recalculation.service';
export * from './scheduler.service';
import { SchedulerService } from './scheduler.service';
export * from './tikTak.service';
import { TikTakService } from './tikTak.service';
export * from './viet.service';
import { VietService } from './viet.service';
export const APIS = [ArticleService, ClientService, DefaultService, HealthService, JobService, OrderService, OrderBundleService, OrderedArticleService, RecalculationService, SchedulerService, TikTakService, VietService];
