/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserEssential } from './userEssential';


export interface AdditionalWorkload { 
    date: string;
    description: string;
    id: number;
    minutes: number;
    user: UserEssential;
}

