/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyEventEnum } from './companyEventEnum';


export interface CompanyEventCreate { 
    date: string;
    event_type: CompanyEventEnum;
    title: string;
}
export namespace CompanyEventCreate {
}


