/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalWorkloadCreate } from './additionalWorkloadCreate';
import { ExpenseCreate } from './expenseCreate';
import { DriveCreate } from './driveCreate';
import { JobSectionCreate } from './jobSectionCreate';


export interface WorkDayCreate { 
    additional_workloads: Array<AdditionalWorkloadCreate>;
    drives: Array<DriveCreate>;
    eating_place_id: number;
    expenses: Array<ExpenseCreate>;
    job_sections: Array<JobSectionCreate>;
    minutes: number;
}

