/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type ContactTypeEnum = 'supplier' | 'client' | 'business' | 'management';

export const ContactTypeEnum = {
    Supplier: 'supplier' as ContactTypeEnum,
    Client: 'client' as ContactTypeEnum,
    Business: 'business' as ContactTypeEnum,
    Management: 'management' as ContactTypeEnum
};

