/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreate } from './addressCreate';
import { DescriptiveArticleCreate } from './descriptiveArticleCreate';


export interface OutgoingInvoiceCreate { 
    number: string;
    date: string;
    payment_condition: string;
    payment_date: string;
    name: string;
    vat_number: string;
    fiscal_code: string;
    codice_destinatario: string;
    pec: string;
    isCompany: boolean;
    descriptive_articles: Array<DescriptiveArticleCreate>;
    vat_id: number;
    job_id: number;
    address: AddressCreate;
}

