/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserEssential { 
    email: string;
    tel: string;
    firstname: string;
    secondname: string;
    cost: number;
    innovaphone_user: string;
    innovaphone_pass: string;
    notifications: boolean;
    id: number;
    fullname: string;
}

